spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/bookdb
    username: ${DB_USER:book}
    password: ${DB_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

server:
  port: 8080